[package]
name = "deconz"
version = "0.0.1"
authors = ["Michael Killough <michaeljkillough@gmail.com>"]
edition = "2018"

[dependencies]
byteorder = "1.3"
log = "0.4"
tokio = { version = "0.2", features = ["full"] }
tokio-serial = "4.3.3"

